### PR TITLE
User cannot view another user_#96; closes #96

### LINKED ISSUE #96: As a user, I cannot view another user's data

### PR DESCRIPTION
**Pull request by KristaANelson**
Test the case a logged in user cannot view another user's information which is located in the past orders view. 

I also refactored the guest_view_spec to clean up format.

### CODE REVIEW

**Comment by EmilyMB** [comment]
:+1: Way to clean up :smile: 

:watch: for :zzz:

**Comment by mikedao** [comment]
is this done? It looks like only the test file was changed.

**Comment by EmilyMB** [comment]
Yes, I think I/we had already built in the functionality.

**Comment by KristaANelson** [comment]
Correct, functionality already happened to be there and then I refactored the methods to match the format we used on the admin test.

**Pull request merged**
